#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
SCRIPT="$ROOT_DIR/skills/git-human-workflow/scripts/git-human-workflow.sh"
FAILED=0

pass() {
  printf 'ok - %s\n' "$1"
}

fail() {
  printf 'not ok - %s\n' "$1" >&2
  FAILED=1
}

run_case() {
  local name=$1
  shift
  if "$@"; then
    pass "$name"
  else
    fail "$name"
  fi
}

new_repo() {
  local directory
  directory=$(mktemp -d)
  git -C "$directory" init -q
  git -C "$directory" config user.name 'Frank Example'
  git -C "$directory" config user.email 'frank@example.test'
  printf '%s\n' "$directory"
}

make_fake_gh() {
  local directory=$1
  mkdir -p "$directory/bin"
  cat >"$directory/bin/gh" <<'FAKE_GH'
#!/usr/bin/env bash
set -euo pipefail

if [[ ${1:-} == auth && ${2:-} == status ]]; then
  exit 0
fi

if [[ ${1:-} == api && ${2:-} == user ]]; then
  case " ${*:3} " in
    *' .login // empty '*) printf 'frankhub\n' ;;
    *' .name // .login // empty '*) printf 'Frank Hub\n' ;;
    *' .email // empty '*) printf 'frankhub@example.test\n' ;;
    *) printf 'frankhub\n' ;;
  esac
  exit 0
fi

if [[ ${1:-} == api && ${2:-} == user/emails ]]; then
  printf 'frankhub@example.test\n'
  exit 0
fi

printf '%s\n' "$*" >>"${FAKE_GH_LOG:?}"
FAKE_GH
  chmod +x "$directory/bin/gh"
}

test_git_commit_uses_configured_identity() {
  local repo actual
  repo=$(new_repo)
  (
    cd "$repo"
    "$SCRIPT" git commit --allow-empty -m 'Add terminal workflow'
  )
  actual=$(git -C "$repo" log -1 --format='%an <%ae>|%cn <%ce>')
  [[ $actual == 'Frank Example <frank@example.test>|Frank Example <frank@example.test>' ]]
}

test_git_rejects_prohibited_branch() {
  local repo
  repo=$(new_repo)
  (
    cd "$repo"
    ! "$SCRIPT" git switch -c codex-cleanup >/dev/null 2>&1
  )
}

test_git_rejects_marker_in_message_file() {
  local repo message
  repo=$(new_repo)
  message="$repo/message.txt"
  printf '%s\n' 'Prepared by ChatGPT' >"$message"
  (
    cd "$repo"
    ! "$SCRIPT" git commit --allow-empty -F "$message" >/dev/null 2>&1
  )
}

test_sanitize_text_removes_marker_lines() {
  local output
  output=$(printf 'Keep this line\nGenerated by AI\nKeep this too\n' | "$SCRIPT" sanitize-text)
  [[ $output == $'Keep this line\nKeep this too' ]]
}

test_hooks_block_bad_plain_commit_messages() {
  local repo
  repo=$(new_repo)
  (
    cd "$repo"
    "$SCRIPT" install-repo-hooks >/dev/null
    ! git commit --allow-empty -m 'Prepared by OpenAI' >/dev/null 2>&1
    git commit --allow-empty -m 'Use checked command line workflow' >/dev/null
  )
}

test_gh_forwards_checked_issue_and_pr() {
  local temporary repo log
  temporary=$(mktemp -d)
  repo=$(new_repo)
  log="$temporary/gh.log"
  make_fake_gh "$temporary"
  (
    cd "$repo"
    PATH="$temporary/bin:$PATH" FAKE_GH_LOG="$log" \
      "$SCRIPT" gh issue create --title 'Verify issue command' --body 'This is a checked issue.'
    PATH="$temporary/bin:$PATH" FAKE_GH_LOG="$log" \
      "$SCRIPT" gh pr create --title 'Verify pull request command' --body 'This is a checked pull request.'
  )
  grep -qx 'issue create --title Verify issue command --body This is a checked issue.' "$log" &&
    grep -qx 'pr create --title Verify pull request command --body This is a checked pull request.' "$log"
}

test_gh_rejects_marker_in_api_input() {
  local temporary repo payload log
  temporary=$(mktemp -d)
  repo=$(new_repo)
  payload="$temporary/payload.json"
  log="$temporary/gh.log"
  printf '%s\n' '{"body":"Authored by Copilot"}' >"$payload"
  make_fake_gh "$temporary"
  (
    cd "$repo"
    ! PATH="$temporary/bin:$PATH" FAKE_GH_LOG="$log" \
      "$SCRIPT" gh api repos/example/issues --method POST --input "$payload" >/dev/null 2>&1
  )
}

test_gh_checks_stdin_payload_and_blocks_web_flow() {
  local temporary repo log
  temporary=$(mktemp -d)
  repo=$(new_repo)
  log="$temporary/gh.log"
  make_fake_gh "$temporary"
  (
    cd "$repo"
    printf '%s\n' '{"body":"Checked payload"}' | PATH="$temporary/bin:$PATH" FAKE_GH_LOG="$log" \
      "$SCRIPT" gh api repos/example/issues --method POST --input -
    ! PATH="$temporary/bin:$PATH" FAKE_GH_LOG="$log" \
      "$SCRIPT" gh issue create --web --title 'Blocked browser flow' --body 'Ignored' >/dev/null 2>&1
  )
  grep -q '^api repos/example/issues --method POST --input ' "$log"
}

run_case 'git commit uses configured identity' test_git_commit_uses_configured_identity
run_case 'git rejects prohibited branch' test_git_rejects_prohibited_branch
run_case 'git rejects marker in message file' test_git_rejects_marker_in_message_file
run_case 'sanitize text removes marker lines' test_sanitize_text_removes_marker_lines
run_case 'hooks block bad plain commit messages' test_hooks_block_bad_plain_commit_messages
run_case 'gh forwards checked issue and pull request' test_gh_forwards_checked_issue_and_pr
run_case 'gh rejects marker in API input' test_gh_rejects_marker_in_api_input
run_case 'gh checks stdin payload and blocks web flow' test_gh_checks_stdin_payload_and_blocks_web_flow

[[ $FAILED -eq 0 ]]
